// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCNrsvk9N5NSekIUab58bniJ98CYoB9s',
    appId: '1:253865129152:web:44d4fae9e5390adee6e925',
    messagingSenderId: '253865129152',
    projectId: 'alphaa-723c5',
    authDomain: 'alphaa-723c5.firebaseapp.com',
    storageBucket: 'alphaa-723c5.firebasestorage.app',
    measurementId: 'G-8N1L2EEKNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQy9i7AncOj33eIkchRbextI4MFnfJyc',
    appId: '1:253865129152:android:b83d3cbc3743910fe6e925',
    messagingSenderId: '253865129152',
    projectId: 'alphaa-723c5',
    storageBucket: 'alphaa-723c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGn9gH_wyB_6Wej4ZUFB9sFQwIgSF2I2I',
    appId: '1:253865129152:ios:a53a5c992a51d2ebe6e925',
    messagingSenderId: '253865129152',
    projectId: 'alphaa-723c5',
    storageBucket: 'alphaa-723c5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGn9gH_wyB_6Wej4ZUFB9sFQwIgSF2I2I',
    appId: '1:253865129152:ios:a53a5c992a51d2ebe6e925',
    messagingSenderId: '253865129152',
    projectId: 'alphaa-723c5',
    storageBucket: 'alphaa-723c5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLCNrsvk9N5NSekIUab58bniJ98CYoB9s',
    appId: '1:253865129152:web:6805329b911488a3e6e925',
    messagingSenderId: '253865129152',
    projectId: 'alphaa-723c5',
    authDomain: 'alphaa-723c5.firebaseapp.com',
    storageBucket: 'alphaa-723c5.firebasestorage.app',
    measurementId: 'G-VRM9TPXJC0',
  );
}
